/**
 * The three prototype weapons that prove the weapon-driven model: Crude Knife,
 * Wooden Spear, Stone Axe. Each is a distinct point in the
 * reach / weight / commitment space. Importing this module registers them.
 *
 * Damage is authored at combat scale (the legacy swing did ~60), independent of
 * the tiny `WeaponTrait.damage` on the item; the runtime scales these by the
 * player's attackDamage for level progression.
 */
import { registerWeaponDefinition } from "./weapon-registry";
import type { WeaponDefinition } from "./weapon-types";

const TILE = 64;

export const CRUDE_KNIFE_DEF: WeaponDefinition = {
  id: "weapon.crude_knife",
  name: "crude knife",
  family: "knife",
  baseDamage: 22,
  handling: {
    weightClass: "light",
    baseReachPx: TILE * 0.9,
    baseRecoveryMs: 200,
    baseStaminaCost: 6,
    stanceMoveSpeedMultiplier: 0.75,
    attackMoveSpeedMultiplier: 0.6,
  },
  guard: {
    moveSpeedMultiplier: 0.72,
    frontalArcDegrees: 105,
    reductionPct: 0.45,
    staminaCostMultiplier: 0.45,
    breakFeedback: "guard_broken",
  },
  animationProfile: "small_slash",
  soundProfile: "knife",
  statModifiers: [{ stat: "moveSpeed", op: "mult", value: 1.05 }],
  attacks: {
    // tap: quick stab
    quick: {
      id: "knife.quick",
      name: "quick stab",
      inputKind: "tap",
      damageType: "pierce",
      damageMultiplier: 1,
      staminaCostMultiplier: 1,
      windupMs: 95,
      activeMs: 85,
      recoveryMs: 170,
      hitShape: { kind: "capsule", lengthPx: TILE * 1.25, widthPx: 44 },
      movement: { moveSpeedMultiplier: 0.72, lungePx: 22 },
      hitOriginOffsetPx: TILE * 0.12,
      comboWindowMs: 420,
      presentation: { trail: "thrust", pose: "quick" },
    },
    // stance tap: precise cut
    stanceSpecial: {
      id: "knife.precise_cut",
      name: "precise cut",
      inputKind: "stance_tap",
      damageType: "slash",
      damageMultiplier: 1.4,
      staminaCostMultiplier: 1.2,
      windupMs: 120,
      activeMs: 80,
      recoveryMs: 220,
      hitShape: { kind: "capsule", lengthPx: TILE * 1.35, widthPx: 38 },
      movement: { moveSpeedMultiplier: 0.65, lungePx: 30 },
      hitOriginOffsetPx: TILE * 0.15,
      comboWindowMs: 420,
      presentation: { trail: "thrust", pose: "extended" },
    },
    // swipe: carving slash that bleeds
    swipe: {
      id: "knife.carving_slash",
      name: "carving slash",
      inputKind: "swipe",
      damageType: "slash",
      damageMultiplier: 1.2,
      staminaCostMultiplier: 1.1,
      windupMs: 90,
      activeMs: 110,
      recoveryMs: 240,
      hitShape: { kind: "capsule", lengthPx: TILE * 1.45, widthPx: 44 },
      movement: { moveSpeedMultiplier: 0.68, lungePx: 28 },
      hitOriginOffsetPx: TILE * 0.18,
      comboWindowMs: 460,
      presentation: { trail: "arc", pose: "extended" },
      statusEffects: [{ kind: "bleed", chancePct: 60, magnitude: 3, durationSec: 6, tickEverySec: 2 }],
    },
  },
  extraAttacks: {
    "knife.follow_cut": {
      id: "knife.follow_cut",
      name: "follow cut",
      inputKind: "tap",
      damageType: "slash",
      damageMultiplier: 1.15,
      staminaCostMultiplier: 1,
      windupMs: 80,
      activeMs: 85,
      recoveryMs: 150,
      hitShape: { kind: "capsule", lengthPx: TILE * 1.35, widthPx: 46 },
      movement: { moveSpeedMultiplier: 0.75, lungePx: 20 },
      hitOriginOffsetPx: TILE * 0.15,
      comboWindowMs: 390,
      presentation: { trail: "arc", pose: "quick" },
      statusEffects: [{ kind: "bleed", chancePct: 45, magnitude: 2, durationSec: 5, tickEverySec: 2 }],
    },
    "knife.exit_cut": {
      id: "knife.exit_cut",
      name: "exit cut",
      inputKind: "tap",
      damageType: "slash",
      damageMultiplier: 1.3,
      staminaCostMultiplier: 1.15,
      windupMs: 80,
      activeMs: 90,
      recoveryMs: 210,
      hitShape: { kind: "arc", radiusPx: TILE * 1.12, arcDegrees: 96 },
      movement: { moveSpeedMultiplier: 0.7, retreatPx: 34 },
      comboWindowMs: 0,
      presentation: { trail: "arc", pose: "guarded" },
      statusEffects: [{ kind: "bleed", chancePct: 70, magnitude: 3, durationSec: 6, tickEverySec: 2 }],
    },
  },
  comboLinks: [
    { fromAttackId: "knife.quick", inputKind: "tap", toAttackId: "knife.follow_cut" },
    { fromAttackId: "knife.follow_cut", inputKind: "tap", toAttackId: "knife.exit_cut" },
  ],
};

export const WOODEN_SPEAR_DEF: WeaponDefinition = {
  id: "weapon.wooden_spear",
  name: "wooden spear",
  family: "spear",
  baseDamage: 30,
  handling: {
    weightClass: "medium",
    baseReachPx: TILE * 2.4,
    baseRecoveryMs: 360,
    baseStaminaCost: 10,
    stanceMoveSpeedMultiplier: 0.55,
    attackMoveSpeedMultiplier: 0.35,
  },
  guard: {
    moveSpeedMultiplier: 0.52,
    frontalArcDegrees: 130,
    reductionPct: 0.62,
    staminaCostMultiplier: 0.48,
    breakFeedback: "guard_broken",
  },
  animationProfile: "straight_thrust",
  soundProfile: "spear",
  statModifiers: [{ stat: "moveSpeed", op: "mult", value: 0.95 }],
  attacks: {
    // tap: poke
    quick: {
      id: "spear.poke",
      name: "poke",
      inputKind: "tap",
      damageType: "pierce",
      damageMultiplier: 1,
      staminaCostMultiplier: 1,
      windupMs: 110,
      activeMs: 100,
      recoveryMs: 320,
      hitShape: { kind: "capsule", lengthPx: TILE * 2.4, widthPx: 34 },
      movement: { moveSpeedMultiplier: 0.45, lungePx: 18 },
      hitOriginOffsetPx: TILE * 0.2,
      comboWindowMs: 520,
      presentation: { trail: "thrust", pose: "extended" },
      techniqueId: "spear_close_range_penalty",
    },
    // stance hold: aimed thrust
    charged: {
      id: "spear.aimed_thrust",
      name: "aimed thrust",
      inputKind: "stance_hold",
      damageType: "pierce",
      damageMultiplier: 1.7,
      staminaCostMultiplier: 1.5,
      windupMs: 220,
      activeMs: 110,
      recoveryMs: 360,
      hitShape: { kind: "capsule", lengthPx: TILE * 2.8, widthPx: 34 },
      movement: { moveSpeedMultiplier: 0.25, lungePx: 44, turnLock: true },
      hitOriginOffsetPx: TILE * 0.25,
      comboWindowMs: 420,
      presentation: { trail: "thrust", pose: "committed" },
      techniqueId: "spear_close_range_penalty",
    },
    // stance swipe: driving thrust (technique reworked from the old combo in Phase 5)
    thrust: {
      id: "spear.driving_thrust",
      name: "driving thrust",
      inputKind: "stance_swipe",
      damageType: "pierce",
      damageMultiplier: 1.5,
      staminaCostMultiplier: 1.6,
      windupMs: 140,
      activeMs: 140,
      recoveryMs: 300,
      hitShape: { kind: "capsule", lengthPx: TILE * 2.6, widthPx: 42 },
      movement: { moveSpeedMultiplier: 0.3, lungePx: 64, turnLock: true },
      hitOriginOffsetPx: TILE * 0.28,
      comboWindowMs: 360,
      presentation: { trail: "thrust", pose: "committed" },
      techniqueId: "spear_close_range_penalty",
    },
  },
  extraAttacks: {
    "spear.second_poke": {
      id: "spear.second_poke",
      name: "second poke",
      inputKind: "tap",
      damageType: "pierce",
      damageMultiplier: 1.15,
      staminaCostMultiplier: 1.05,
      windupMs: 90,
      activeMs: 95,
      recoveryMs: 280,
      hitShape: { kind: "capsule", lengthPx: TILE * 2.55, widthPx: 36 },
      movement: { moveSpeedMultiplier: 0.42, lungePx: 22 },
      hitOriginOffsetPx: TILE * 0.22,
      comboWindowMs: 500,
      techniqueId: "spear_close_range_penalty",
      presentation: { trail: "thrust", pose: "extended" },
    },
  },
  comboLinks: [
    { fromAttackId: "spear.poke", inputKind: "tap", toAttackId: "spear.second_poke" },
    { fromAttackId: "spear.second_poke", inputKind: "hold", toAttackId: "spear.aimed_thrust" },
  ],
};

export const STONE_AXE_DEF: WeaponDefinition = {
  id: "weapon.stone_axe",
  name: "stone axe",
  family: "axe",
  baseDamage: 48,
  handling: {
    weightClass: "heavy",
    baseReachPx: TILE * 1.5,
    baseRecoveryMs: 520,
    baseStaminaCost: 16,
    stanceMoveSpeedMultiplier: 0.45,
    attackMoveSpeedMultiplier: 0.2,
  },
  guard: {
    moveSpeedMultiplier: 0.42,
    frontalArcDegrees: 135,
    reductionPct: 0.7,
    staminaCostMultiplier: 0.55,
    breakFeedback: "guard_broken",
  },
  animationProfile: "heavy_chop",
  soundProfile: "axe",
  statModifiers: [{ stat: "moveSpeed", op: "mult", value: 0.85 }],
  attacks: {
    // tap: rough chop
    quick: {
      id: "axe.rough_chop",
      name: "rough chop",
      inputKind: "tap",
      damageType: "chop",
      damageMultiplier: 1,
      staminaCostMultiplier: 1,
      windupMs: 180,
      activeMs: 110,
      recoveryMs: 480,
      hitShape: { kind: "arc", radiusPx: TILE * 1.85, arcDegrees: 118 },
      movement: { moveSpeedMultiplier: 0.2 },
      hitOriginOffsetPx: TILE * 0.1,
      comboWindowMs: 560,
      presentation: { trail: "heavy", pose: "committed" },
      techniqueId: "axe_structure_bonus",
    },
    // hold: heavier chop
    heavy: {
      id: "axe.heavy_chop",
      name: "heavy chop",
      inputKind: "hold",
      damageType: "chop",
      damageMultiplier: 1.5,
      staminaCostMultiplier: 1.4,
      windupMs: 260,
      activeMs: 120,
      recoveryMs: 560,
      hitShape: { kind: "arc", radiusPx: TILE * 2.0, arcDegrees: 128 },
      movement: { moveSpeedMultiplier: 0.15, lungePx: 28 },
      hitOriginOffsetPx: TILE * 0.12,
      comboWindowMs: 560,
      presentation: { trail: "heavy", pose: "committed" },
      techniqueId: "axe_structure_bonus",
    },
    // stance hold: committed overhead (reworked from fell-sweep in Phase 5)
    charged: {
      id: "axe.committed_overhead",
      name: "committed overhead",
      inputKind: "stance_hold",
      damageType: "chop",
      damageMultiplier: 2.2,
      staminaCostMultiplier: 1.8,
      windupMs: 380,
      activeMs: 130,
      recoveryMs: 640,
      hitShape: { kind: "circle", radiusPx: TILE * 1.55 },
      movement: { moveSpeedMultiplier: 0.1, lungePx: 36, turnLock: true },
      hitOriginOffsetPx: TILE * 0.2,
      comboWindowMs: 0,
      presentation: { trail: "heavy", pose: "committed" },
      techniqueId: "axe_structure_bonus",
    },
  },
  extraAttacks: {
    "axe.follow_cleave": {
      id: "axe.follow_cleave",
      name: "follow cleave",
      inputKind: "tap",
      damageType: "chop",
      damageMultiplier: 1.25,
      staminaCostMultiplier: 1.2,
      windupMs: 210,
      activeMs: 115,
      recoveryMs: 520,
      hitShape: { kind: "arc", radiusPx: TILE * 1.95, arcDegrees: 132 },
      movement: { moveSpeedMultiplier: 0.18, lungePx: 20 },
      hitOriginOffsetPx: TILE * 0.12,
      comboWindowMs: 520,
      techniqueId: "axe_structure_bonus",
      presentation: { trail: "heavy", pose: "committed" },
    },
  },
  comboLinks: [
    { fromAttackId: "axe.rough_chop", inputKind: "tap", toAttackId: "axe.follow_cleave" },
    { fromAttackId: "axe.follow_cleave", inputKind: "hold", toAttackId: "axe.heavy_chop" },
    { fromAttackId: "axe.heavy_chop", inputKind: "stance_hold", toAttackId: "axe.committed_overhead" },
  ],
};

registerWeaponDefinition(CRUDE_KNIFE_DEF);
registerWeaponDefinition(WOODEN_SPEAR_DEF);
registerWeaponDefinition(STONE_AXE_DEF);
