import { Category, Rarity, itemId } from "$lib/domain/items/item-types";
import { Item } from "$lib/domain/items/item-builder";
import { TransformInto } from "$lib/domain/items/item-effects";
import {
  Flammable,
  TemperatureSensitive,
  Decayable,
  TanninSource,
  BindingMaterial,
  Sealant,
  AttractsPredators,
  ArmorMaterial,
  InsulationMaterial,
} from "$lib/domain/items/item-traits";


export const materialItems = {
  stone: Item({
    id: itemId("stone"),
    name: "Stone",
    description: "A raw chunk of stone. Rough and heavy.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 30 },
  }),
  stick: Item({
    id: itemId("stick"),
    name: "Stick",
    description: "A dry fallen stick. Light enough to carry by the handful.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pocket", weight: 0.2, stackLimit: 20 },
  }).with(
    Flammable({ ignitionTemp: 95, burnDurationSec: 6, effect: TransformInto(itemId("ash")) })
  ),
  twig_bundle: Item({
    id: itemId("twig_bundle"),
    name: "Twig Bundle",
    description: "A handful of small twigs gathered into a usable bundle of kindling.",
    rarity: Rarity.Common,
    category: Category.Timber,
    icon: "🪵",
    physical: { carryClass: "pack", weight: 0.35, stackLimit: 20 },
  }).with(
    Flammable({ ignitionTemp: 150, burnDurationSec: 20, effect: TransformInto(itemId("ash")) })
  ),
  branch: Item({
    id: itemId("branch"),
    name: "Branch",
    description: "A thicker branch, useful as crude structure or tool stock.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 0.8, stackLimit: 12 },
  }).with(
    Flammable({ ignitionTemp: 105, burnDurationSec: 10, effect: TransformInto(itemId("charcoal")) })
  ),
  flint_shard: Item({
    id: itemId("flint_shard"),
    name: "Flint Shard",
    description: "A jagged stone shard with a pale edge.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pocket", weight: 0.15, stackLimit: 20 },
  }),
  grass_fiber: Item({
    id: itemId("grass_fiber"),
    name: "Grass Fiber",
    description: "Pulled strands of tough grass that can bind small tools.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 40 },
  }),
  leaves: Item({
    id: itemId("leaves"),
    name: "Leaves",
    description: "Dry leaf litter. Useful as tinder, terrible near flame.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.03, stackLimit: 50 },
  }).with(
    Flammable({ ignitionTemp: 70, burnDurationSec: 3, effect: TransformInto(itemId("ash")) })
  ),
  dry_leaves: Item({
    id: itemId("dry_leaves"),
    name: "Dry Leaves",
    description: "Crisp leaves that catch flame easily. Bad near sparks, useful near purpose.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🍂",
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 50 },
  }).with(
    Flammable({ ignitionTemp: 90, burnDurationSec: 8, effect: TransformInto(itemId("ash")) })
  ),
  green_leaves: Item({
    id: itemId("green_leaves"),
    name: "Green Leaves",
    description: "Fresh leaves, damp and flexible. Useful for wrapping, padding, and crude medicine.",
    rarity: Rarity.Common,
    category: Category.Herb,
    icon: "🍃",
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 50 },
  }).with(
    Decayable({ lifespanSec: 900, effect: TransformInto(itemId("dry_leaves")) })
  ),
  bark: Item({
    id: itemId("bark"),
    name: "Bark",
    description: "Rough bark stripped from fallen wood.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.1, stackLimit: 30 },
  }).with(
    Flammable({ ignitionTemp: 90, burnDurationSec: 5, effect: TransformInto(itemId("charcoal")) })
  ),
  oak_bark: Item({
    id: itemId("oak_bark"),
    name: "Oak Bark",
    description: "Rough bark rich with bitter tannins. Useful for hide work and wound washing.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    icon: "🌳",
    physical: { carryClass: "pack", weight: 0.2, stackLimit: 25 },
  }).with(TanninSource(1)),
  vine: Item({
    id: itemId("vine"),
    name: "Vine",
    description: "A flexible forest vine. Stronger than grass, worse than proper rope.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🌿",
    physical: { carryClass: "pack", weight: 0.25, stackLimit: 20 },
  }).with(BindingMaterial(1)),
  clay: Item({
    id: itemId("clay"),
    name: "Clay",
    description: "Wet clay that holds shape when pressed.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.8, stackLimit: 20 },
  }).with(
    TemperatureSensitive({ minSafeTemp: -100, maxSafeTemp: 90, effect: TransformInto(itemId("hardened_clay")) })
  ),
  hardened_clay: Item({
    id: itemId("hardened_clay"),
    name: "Hardened Clay",
    description: "Clay baked firm enough for crude containers and structure.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 20 },
  }),
  ash: Item({
    id: itemId("ash"),
    name: "Ash",
    description: "Fine grey ash left by burned tinder.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    physical: { carryClass: "pocket", weight: 0.02, stackLimit: 50 },
  }),
  copper_ore: Item({
    id: itemId("copper_ore"),
    name: "Copper Ore",
    description: "Veins of copper running through rock.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.4, stackLimit: 20 },
  }),
  tinder_bundle: Item({
    id: itemId("tinder_bundle"),
    name: "Tinder Bundle",
    description: "A little nest of dry leaf and bark for coaxing flame.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 20 },
  }).with(
    Flammable({ ignitionTemp: 55, burnDurationSec: 4, effect: TransformInto(itemId("ash")) })
  ),
  firewood_bundle: Item({
    id: itemId("firewood_bundle"),
    name: "Firewood Bundle",
    description: "Tied branches that feed a campfire longer than loose sticks.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.8, stackLimit: 8 },
  }).with(
    Flammable({ ignitionTemp: 105, burnDurationSec: 24, effect: TransformInto(itemId("charcoal")) })
  ),
  binding_cord: Item({
    id: itemId("binding_cord"),
    name: "Binding Cord",
    description: "Twisted fiber and bark, good enough for crude tools.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.06, stackLimit: 30 },
  }),
  grass_cord: Item({
    id: itemId("grass_cord"),
    name: "Grass Cord",
    description: "Twisted grass fiber. Weak, but much better than loose strands.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🧵",
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 50 },
  }).with(BindingMaterial(1)),
  bark_rope: Item({
    id: itemId("bark_rope"),
    name: "Bark Rope",
    description: "Bark strips twisted into rough rope. Stiff, scratchy, and useful.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🪢",
    physical: { carryClass: "pack", weight: 0.25, stackLimit: 25 },
  }).with(BindingMaterial(2)),
  mud: Item({
    id: itemId("mud"),
    name: "Mud",
    description: "Wet earth from a water edge. Messy, but it seals gaps.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 20 },
  }),
  sealing_paste: Item({
    id: itemId("sealing_paste"),
    name: "Sealing Paste",
    description: "Mud and ash worked into a dark paste.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.45, stackLimit: 20 },
  }).with(Sealant(1)),
  iron_ore: Item({
    id: itemId("iron_ore"),
    name: "Iron Ore",
    description: "Deep-vein iron with crystalline structure.",
    rarity: Rarity.Uncommon,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.6, stackLimit: 20 },
  }),
  silver_ore: Item({
    id: itemId("silver_ore"),
    name: "Silver Ore",
    description: "Shining silver ore, cool to the touch.",
    rarity: Rarity.Rare,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.3, stackLimit: 20 },
  }),
  wood: Item({
    id: itemId("wood"),
    name: "Wood",
    description: "A log of raw timber. Cuts, burns, and builds.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.5, stackLimit: 20 },
  }).with(
    Flammable({ ignitionTemp: 120, burnDurationSec: 15, effect: TransformInto(itemId("charcoal")) })
  ),
  stone_block: Item({
    id: itemId("stone_block"),
    name: "Stone Block",
    description: "Refined block of cut stone.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 2, stackLimit: 20 },
  }),
  copper_ingot: Item({
    id: itemId("copper_ingot"),
    name: "Copper Ingot",
    description: "A pure bar of smelted copper.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 1, stackLimit: 20 },
  }),
  iron_ingot: Item({
    id: itemId("iron_ingot"),
    name: "Iron Ingot",
    description: "A solid bar of refined iron.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 20 },
  }),
  silver_ingot: Item({
    id: itemId("silver_ingot"),
    name: "Silver Ingot",
    description: "A glistening bar of sterling silver.",
    rarity: Rarity.Rare,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 1, stackLimit: 20 },
  }),
  plank: Item({
    id: itemId("plank"),
    name: "Plank",
    description: "A smooth plank of sawed timber.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.6, stackLimit: 30 },
  }),
  ice_block: Item({
    id: itemId("ice_block"),
    name: "Ice Block",
    description: "A solid, freezing block of glacial ice. Melts rapidly in warm areas.",
    rarity: Rarity.Uncommon,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1, stackLimit: 10 },
  }).with(
    TemperatureSensitive({ minSafeTemp: -100, maxSafeTemp: 0, effect: TransformInto(itemId("clean_water")) })
  ),
  charcoal: Item({
    id: itemId("charcoal"),
    name: "Charcoal",
    description: "Slow-burned wood. Hotter and cleaner than coal.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.2, stackLimit: 30 },
  }),
  volatile_ash: Item({
    id: itemId("volatile_ash"),
    name: "Volatile Ash",
    description: "Grey, inert ash residue from failed Crucible synthesis or decay.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    physical: { carryClass: "pocket", weight: 0.02, stackLimit: 50 },
  }),
  flat_stone: Item({
    id: itemId("flat_stone"),
    name: "Flat Stone",
    description: "A broad, smooth stone. Good surface for crushing or as a crude work base.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.0, stackLimit: 10 },
  }),
  resin: Item({
    id: itemId("resin"),
    name: "Resin",
    description: "Sticky amber sap from a wounded tree. Catches flame well and seals gaps.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.1, stackLimit: 20 },
  }).with(
    Flammable({ ignitionTemp: 65, burnDurationSec: 8, effect: TransformInto(itemId("ash")) })
  ),
  pine_cone: Item({
    id: itemId("pine_cone"),
    name: "Pine Cone",
    description: "A dry pine cone packed with resinous scales. Lights easily and pops in flame.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.08, stackLimit: 20 },
  }).with(
    Flammable({ ignitionTemp: 75, burnDurationSec: 5, effect: TransformInto(itemId("ash")) })
  ),
  raw_hide: Item({
    id: itemId("raw_hide"),
    name: "Raw Hide",
    description: "Fresh animal hide. Heavy, wet, and useful if treated before it rots.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🟫",
    physical: { carryClass: "pack", weight: 1.0, stackLimit: 10 },
  }).with(
    Decayable({ lifespanSec: 900, effect: TransformInto(itemId("spoiled_hide")) })
  ),
  spoiled_hide: Item({
    id: itemId("spoiled_hide"),
    name: "Spoiled Hide",
    description: "Rotting hide. It stinks, tears poorly, and invites regret.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🟫",
    physical: { carryClass: "pack", weight: 0.9, stackLimit: 10 },
  }).with(AttractsPredators(1)),
  dried_hide: Item({
    id: itemId("dried_hide"),
    name: "Dried Hide",
    description: "Hide dried stiff. Better than fresh rot, worse than treated leather.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🟫",
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 15 },
  }).with(ArmorMaterial(1)),
  cured_hide: Item({
    id: itemId("cured_hide"),
    name: "Cured Hide",
    description: "Hide treated with tannins and smoke. Usable for clothing and gear.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    icon: "🟫",
    physical: { carryClass: "pack", weight: 0.65, stackLimit: 15 },
  }).with(ArmorMaterial(2), InsulationMaterial(1)),
  rabbit_pelt: Item({
    id: itemId("rabbit_pelt"),
    name: "Rabbit Pelt",
    description: "Small soft pelt. Not enough alone, but useful in layers.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🐇",
    physical: { carryClass: "pocket", weight: 0.18, stackLimit: 25 },
  }).with(InsulationMaterial(1)),
  deer_hide: Item({
    id: itemId("deer_hide"),
    name: "Deer Hide",
    description: "Large hide from a deer. Good base for wraps and shelter work.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "🦌",
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 8 },
  }).with(InsulationMaterial(2)),
  boar_hide: Item({
    id: itemId("boar_hide"),
    name: "Boar Hide",
    description: "Tough hide from a boar. Harder to work, better for rough protection.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    icon: "🐗",
    physical: { carryClass: "pack", weight: 1.4, stackLimit: 8 },
  }).with(ArmorMaterial(2)),
  wolf_pelt: Item({
    id: itemId("wolf_pelt"),
    name: "Wolf Pelt",
    description: "Thick predator pelt. Warm, heavy, and not easily taken.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    icon: "🐺",
    physical: { carryClass: "pack", weight: 1.3, stackLimit: 8 },
  }).with(InsulationMaterial(3)),
  small_bone: Item({
    id: itemId("small_bone"),
    name: "Small Bone",
    description: "A thin bone suited for needles, pins, and delicate tool work.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 30 },
  }),
  bone: Item({
    id: itemId("bone"),
    name: "Bone",
    description: "A sturdy animal bone. It can be shaped into tools, points, or fasteners.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.25, stackLimit: 20 },
  }),
  bone_shard: Item({
    id: itemId("bone_shard"),
    name: "Bone Shard",
    description: "A sharp splinter of bone. Could be worked into a crude point or needle.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.1, stackLimit: 20 },
  }),
  tendon: Item({
    id: itemId("tendon"),
    name: "Tendon",
    description: "Tough animal tendon. When dried, it becomes strong binding material.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "〰️",
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 40 },
  }).with(
    BindingMaterial(2),
    Decayable({ lifespanSec: 900, effect: TransformInto(itemId("dried_tendon")) })
  ),
  dried_tendon: Item({
    id: itemId("dried_tendon"),
    name: "Dried Tendon",
    description: "Dried sinew that binds better than grass or bark.",
    rarity: Rarity.Common,
    category: Category.Component,
    icon: "〰️",
    physical: { carryClass: "pocket", weight: 0.04, stackLimit: 50 },
  }).with(BindingMaterial(3)),
  fang: Item({
    id: itemId("fang"),
    name: "Fang",
    description: "A predator fang with a clean point. Useful as a sharp component or warning token.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 10 },
  }),
  tusk_shard: Item({
    id: itemId("tusk_shard"),
    name: "Tusk Shard",
    description: "A broken tusk edge from a boar. Heavy, sharp, and awkward.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.12, stackLimit: 10 },
  }),
  antler: Item({
    id: itemId("antler"),
    name: "Antler",
    description: "Hard branching bone from a deer. Useful for handles and tools.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    icon: "🦌",
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 8 },
  }),
  feather: Item({
    id: itemId("feather"),
    name: "Feather",
    description: "A light flight feather. Soft, dry, and useful for fletching or tinder.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.01, stackLimit: 10 },
  }),
  soot: Item({
    id: itemId("soot"),
    name: "Soot",
    description: "Fine black residue from smoky flame. Good for marks, bad for lungs.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    icon: "⚫",
    physical: { carryClass: "pocket", weight: 0.01, stackLimit: 100 },
  }),
  foul_sludge: Item({
    id: itemId("foul_sludge"),
    name: "Foul Sludge",
    description: "A disgusting, useless mixture of alchemical residue.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 0.5, stackLimit: 20 },
  }),
  charred_ash: Item({
    id: itemId("charred_ash"),
    name: "Charred Ash",
    description: "The burnt remnants of a failed experiment.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 0.1, stackLimit: 30 },
  }),
};
