import { Category, Rarity, itemId } from "$lib/domain/items/item-types";
import { Item } from "$lib/domain/items/item-builder";
import { Placeable, RestQuality } from "$lib/domain/items/item-traits";

export const structureItems = {
  campfire_kit: Item({
    id: itemId("campfire_kit"),
    name: "Campfire Kit",
    description: "Stones, tinder, and fuel arranged for a controlled campfire.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "🔥",
    physical: { carryClass: "haul", weight: 3.0, stackLimit: 1 },
  }).with(Placeable("campfire")),
  primitive_work_surface_kit: Item({
    id: itemId("primitive_work_surface_kit"),
    name: "Primitive Work Surface Kit",
    description: "A flat stone and wooden supports for basic crafting work.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "🪨",
    physical: { carryClass: "haul", weight: 5.0, stackLimit: 1 },
  }).with(Placeable("primitive_work_surface")),
  drying_rack_kit: Item({
    id: itemId("drying_rack_kit"),
    name: "Drying Rack Kit",
    description: "A simple frame for drying meat, herbs, and hide.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "🪵",
    physical: { carryClass: "haul", weight: 4.0, stackLimit: 1 },
  }).with(Placeable("drying_rack")),
  marker_sign_kit: Item({
    id: itemId("marker_sign_kit"),
    name: "Marker Sign Kit",
    description: "A crude sign ready to be placed and carved with player-written text.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "🪧",
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 4 },
  }).with(Placeable("marker_sign")),
  crude_shelter_kit: Item({
    id: itemId("crude_shelter_kit"),
    name: "Crude Shelter Kit",
    description: "A bundled frame for a lean-to shelter. Not comfort. Shelter.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "⛺",
    physical: { carryClass: "haul", weight: 6.0, stackLimit: 1 },
  }).with(Placeable("crude_shelter")),
  storage_pile_kit: Item({
    id: itemId("storage_pile_kit"),
    name: "Storage Pile Kit",
    description: "A marked ground pile reinforced with sticks and bark to organize camp storage.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "📦",
    physical: { carryClass: "haul", weight: 3.5, stackLimit: 1 },
  }).with(Placeable("storage_pile")),
  spike_barrier_kit: Item({
    id: itemId("spike_barrier_kit"),
    name: "Spike Barrier Kit",
    description: "Sharpened stakes lashed into a crude barrier against animals.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "🪵",
    physical: { carryClass: "haul", weight: 5.5, stackLimit: 1 },
  }).with(Placeable("spike_barrier")),
  rain_catcher_kit: Item({
    id: itemId("rain_catcher_kit"),
    name: "Rain Catcher Kit",
    description: "A crude frame and hide surface for catching rainwater.",
    rarity: Rarity.Uncommon,
    category: Category.Structure,
    icon: "💧",
    physical: { carryClass: "haul", weight: 4.5, stackLimit: 1 },
  }).with(Placeable("rain_catcher")),
  meat_smoking_rack_kit: Item({
    id: itemId("meat_smoking_rack_kit"),
    name: "Meat Smoking Rack Kit",
    description: "A rack arranged to hold meat in smoke instead of direct flame.",
    rarity: Rarity.Uncommon,
    category: Category.Structure,
    icon: "🍖",
    physical: { carryClass: "haul", weight: 4.5, stackLimit: 1 },
  }).with(Placeable("meat_smoking_rack")),
  simple_bedroll: Item({
    id: itemId("simple_bedroll"),
    name: "Simple Bedroll",
    description: "Layered leaves, hide, and fiber. A poor answer to sleeping on cold dirt.",
    rarity: Rarity.Common,
    category: Category.Structure,
    icon: "️",
    physical: { carryClass: "haul", weight: 3.0, stackLimit: 1 },
  }).with(Placeable("simple_bedroll"), RestQuality(1)),
};
