import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const clothingRecipes: readonly RecipeInput[] = [
  {
    id: "fiber_wraps",
    name: "Fiber Wraps",
    description: "You bind plant fiber into rough protective wraps.",
    category: "clothing",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You bind plant fiber into rough protective wraps.",
    costs: [
      { itemId: "grass_fiber", name: "grass fiber", required: 6 },
      { itemId: "green_leaves", name: "green leaves", required: 2 },
    ],
    output: { itemId: "fiber_wraps", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
  {
    id: "hide_footwraps",
    name: "Hide Footwraps",
    description: "You stitch hide into rough protection for your feet.",
    category: "clothing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You stitch hide into rough protection for your feet.",
    costs: [
      { itemId: "dried_hide", name: "dried hide", required: 1 },
      { itemId: "grass_cord", name: "grass cord", required: 2 },
      { itemId: "bone_needle", name: "bone needle", required: 1 },
    ],
    output: { itemId: "hide_footwraps", qty: 1 },
    process: "assemble",
    durationSec: 25,
  },
  {
    id: "leather_gloves",
    name: "Leather Gloves",
    description: "You stitch cured hide into crude hand protection.",
    category: "clothing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You stitch cured hide into crude hand protection.",
    costs: [
      { itemId: "cured_hide", name: "cured hide", required: 1 },
      { itemId: "dried_tendon", name: "dried tendon", required: 1 },
      { itemId: "bone_needle", name: "bone needle", required: 1 },
    ],
    output: { itemId: "leather_gloves", qty: 1 },
    process: "assemble",
    durationSec: 30,
  },
  {
    id: "hide_cloak",
    name: "Hide Cloak",
    description: "You join larger hide pieces into a cloak against cold nights.",
    category: "clothing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You join larger hide pieces into a cloak against cold nights.",
    costs: [
      { itemId: "dried_hide", name: "dried hide", required: 2 },
      { itemId: "bark_rope", name: "bark rope", required: 1 },
      { itemId: "bone_needle", name: "bone needle", required: 1 },
    ],
    output: { itemId: "hide_cloak", qty: 1 },
    process: "assemble",
    durationSec: 45,
  },
  {
    id: "fur_lined_wrap",
    name: "Fur-Lined Wrap",
    description: "You layer warm pelt against hide to keep the cold from chewing so deeply.",
    category: "clothing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You layer warm pelt against hide to keep the cold from chewing so deeply.",
    costs: [
      { itemId: "cured_hide", name: "cured hide", required: 2 },
      { itemId: "dried_tendon", name: "dried tendon", required: 2 },
      { itemId: "bone_needle", name: "bone needle", required: 1 },
    ],
    output: { itemId: "fur_lined_wrap", qty: 1 },
    process: "assemble",
    durationSec: 50,
  },
  {
    id: "boar_leather_coat",
    name: "Boar Leather Coat",
    description: "You stitch heavy boar hide and cured leather together with sinew.",
    category: "clothing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "The heavy coat fits stiffly, promising serious protection.",
    costs: [
      { itemId: "boar_hide", name: "boar hide", required: 2 },
      { itemId: "cured_hide", name: "cured hide", required: 1 },
      { itemId: "dried_tendon", name: "dried tendon", required: 2 },
      { itemId: "bone_needle", name: "bone needle", required: 1 },
    ],
    output: { itemId: "boar_leather_coat", qty: 1 },
    process: "assemble",
    durationSec: 40,
  },
  {
    id: "stalker_mask",
    name: "Stalker Mask",
    description: "You align predator pelts and fit wolf fangs into a fearsome mask.",
    category: "clothing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "The wolf's empty gaze keeps the wind and cold away.",
    costs: [
      { itemId: "wolf_pelt", name: "wolf pelt", required: 1 },
      { itemId: "fang", name: "fang", required: 2 },
      { itemId: "dried_tendon", name: "dried tendon", required: 1 },
      { itemId: "bone_needle", name: "bone needle", required: 1 },
    ],
    output: { itemId: "stalker_mask", qty: 1 },
    process: "assemble",
    durationSec: 35,
  },
];
