import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const foodRecipes: readonly RecipeInput[] = [
  {
    id: "roasted_root",
    name: "Roasted Root",
    description: "a wild root buried in the embers until soft and edible.",
    requiresCampfire: true,
    category: "food",
    requiredContext: "campfire",
    process: "heat",
    durationSec: 5,
    discoverable: true,
    discoveryText: "It comes out dense and sweet from the heat.",
    feedbackTags: ["fire", "smoke"],
    costs: [{ itemId: "wild_root", name: "wild root", required: 1 }],
    output: { itemId: "roasted_root", qty: 1 },
  },
  {
    id: "roast_wild_root",
    name: "Roast Wild Root (Seed)",
    description: "You roast the root until it softens enough to be decent food.",
    category: "food",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You roast the root until it softens enough to be decent food.",
    costs: [{ itemId: "wild_root", name: "wild root", required: 1 }],
    output: { itemId: "roasted_root", qty: 1 },
    process: "heat",
    durationSec: 18,
  },
  {
    id: "roasted_acorn",
    name: "Roasted Acorn",
    description: "acorns crisped in the fire until their bitterness eases.",
    requiresCampfire: true,
    category: "food",
    requiredContext: "campfire",
    process: "heat",
    durationSec: 4,
    discoverable: true,
    discoveryText: "The shells split and the inside smells nutty.",
    feedbackTags: ["fire"],
    costs: [{ itemId: "acorn", name: "acorn", required: 2 }],
    output: { itemId: "roasted_acorn", qty: 2 },
  },
  {
    id: "roast_acorns",
    name: "Roast Acorns (Seed)",
    description: "You roast acorns until some of the bitterness gives up.",
    category: "food",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You roast acorns until some of the bitterness gives up.",
    costs: [{ itemId: "acorn", name: "acorn", required: 4 }],
    output: { itemId: "roasted_acorn", qty: 4 },
    process: "heat",
    durationSec: 16,
  },
  {
    id: "cooked_meat",
    name: "Cooked Meat",
    description: "meat seared over the fire until safe to eat.",
    requiresCampfire: true,
    category: "food",
    requiredContext: "campfire",
    process: "heat",
    durationSec: 6,
    discoverable: true,
    discoveryText: "The fat drips into the embers and the smell changes.",
    feedbackTags: ["fire", "smoke"],
    costs: [{ itemId: "raw_meat", name: "raw meat", required: 1 }],
    output: { itemId: "cooked_meat", qty: 1 },
  },
  {
    id: "cook_raw_meat",
    name: "Cook Raw Meat (Seed)",
    description: "You cook meat until it becomes safer food instead of a gamble.",
    category: "food",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You cook meat until it becomes safer food instead of a gamble.",
    costs: [{ itemId: "raw_meat", name: "raw meat", required: 1 }],
    output: { itemId: "cooked_meat", qty: 1 },
    process: "heat",
    durationSec: 20,
  },
  {
    id: "cook_small_meat",
    name: "Cook Small Raw Meat",
    description: "You cook a small strip of meat quickly over flame.",
    category: "food",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You cook a small strip of meat quickly over flame.",
    costs: [{ itemId: "raw_small_meat", name: "small raw meat", required: 1 }],
    output: { itemId: "cooked_meat", qty: 1 },
    process: "heat",
    durationSec: 14,
  },
  {
    id: "cook_fatty_meat",
    name: "Cook Fatty Meat",
    description: "You render some fat while cooking the meat.",
    category: "food",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You render some fat while cooking the meat.",
    costs: [{ itemId: "fatty_meat", name: "fatty meat", required: 1 }],
    output: { itemId: "cooked_meat", qty: 1 },
    process: "heat",
    durationSec: 22,
  },
  {
    id: "bone_broth",
    name: "Bone Broth",
    description: "You boil bones in water until the pot gives you something warm back.",
    category: "food",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You boil bones in water until the pot gives you something warm back.",
    costs: [
      { itemId: "small_bone", name: "small bone", required: 2 },
      { itemId: "clean_water", name: "clean water", required: 1 },
    ],
    output: { itemId: "bone_broth", qty: 1 },
    process: "boil",
    durationSec: 45,
  },
  {
    id: "dried_meat",
    name: "Dried Meat",
    description: "meat hung until the moisture leaves it. lasts far longer.",
    category: "food",
    requiredContext: "drying_rack",
    process: "dry",
    durationSec: 20,
    discoverable: true,
    discoveryText: "The texture changes, the rot smell fades.",
    feedbackTags: ["dry"],
    costs: [{ itemId: "raw_meat", name: "raw meat", required: 2 }],
    output: { itemId: "dried_meat", qty: 1 },
  },
  {
    id: "dry_raw_meat",
    name: "Dry Raw Meat (Seed)",
    description: "Air slowly pulls moisture from the meat, making it last longer.",
    category: "food",
    requiredContext: "drying_rack",
    discoverable: true,
    discoveryText: "Air slowly pulls moisture from the meat, making it last longer.",
    costs: [{ itemId: "raw_meat", name: "raw meat", required: 1 }],
    output: { itemId: "dried_meat", qty: 1 },
    process: "dry",
    durationSec: 120,
  },
  {
    id: "dry_small_meat",
    name: "Dry Small Raw Meat",
    description: "Small cuts dry faster and become portable food.",
    category: "food",
    requiredContext: "drying_rack",
    discoverable: true,
    discoveryText: "Small cuts dry faster and become portable food.",
    costs: [{ itemId: "raw_small_meat", name: "small raw meat", required: 1 }],
    output: { itemId: "dried_meat", qty: 1 },
    process: "dry",
    durationSec: 90,
  },
  {
    id: "smoke_meat",
    name: "Smoke Meat",
    description: "You preserve meat in smoke instead of letting the forest take it back.",
    category: "food",
    requiredContext: "meat_smoking_rack",
    discoverable: true,
    discoveryText: "You preserve meat in smoke instead of letting the forest take it back.",
    costs: [
      { itemId: "raw_meat", name: "raw meat", required: 1 },
      { itemId: "charcoal", name: "charcoal", required: 1 },
    ],
    output: { itemId: "smoked_meat", qty: 1 },
    process: "smoke",
    durationSec: 160,
  },
  {
    id: "smoke_small_meat",
    name: "Smoke Small Meat",
    description: "You smoke small cuts into better trail food.",
    category: "food",
    requiredContext: "meat_smoking_rack",
    discoverable: true,
    discoveryText: "You smoke small cuts into better trail food.",
    costs: [
      { itemId: "raw_small_meat", name: "small raw meat", required: 1 },
      { itemId: "charcoal", name: "charcoal", required: 1 },
    ],
    output: { itemId: "smoked_meat", qty: 1 },
    process: "smoke",
    durationSec: 120,
  },
  {
    id: "smoked_meat_pemmican",
    name: "Smoked Pemmican",
    description: "You pound smoked meat, berries, and rendered fat together into dense trail rations.",
    category: "food",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "The mixture binds into dense, high-energy cakes.",
    costs: [
      { itemId: "smoked_meat", name: "smoked meat", required: 1, substitutes: [{ itemId: "cooked_meat", name: "cooked meat", required: 1 }, { itemId: "dried_meat", name: "dried meat", required: 1 }] },
      { itemId: "berries", name: "berries", required: 2 },
      { itemId: "rendered_fat", name: "rendered fat", required: 1 },
    ],
    output: { itemId: "smoked_meat_pemmican", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
];
