import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const fuelRecipes: readonly RecipeInput[] = [
  {
    id: "bundle_twigs",
    name: "Bundle Twigs",
    description: "You gather small twigs into a bundle of usable kindling.",
    category: "fuel_fire",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You gather small twigs into a bundle of usable kindling.",
    costs: [{ itemId: "stick", name: "stick", required: 4 }],
    output: { itemId: "twig_bundle", qty: 1 },
    process: "assemble",
    durationSec: 3,
  },
  {
    id: "charcoal",
    name: "Charcoal",
    description: "slow-burned wood for steady heat.",
    requiresCampfire: true,
    category: "fuel_fire",
    requiredContext: "campfire",
    process: "burn",
    feedbackTags: ["smoke", "ash", "fire"],
    costs: [{ itemId: "wood", name: "Wood", required: 2 }],
  },
  {
    id: "make_charcoal_from_branch",
    name: "Char Branch",
    description: "You burn wood low and slow enough to leave useful charcoal.",
    category: "fuel_fire",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You burn wood low and slow enough to leave useful charcoal.",
    costs: [{ itemId: "branch", name: "branch", required: 1 }],
    output: { itemId: "charcoal", qty: 1 },
    process: "burn",
    durationSec: 40,
  },
  {
    id: "make_charcoal_from_firewood",
    name: "Char Firewood",
    description: "You reduce a firewood bundle into usable charcoal.",
    category: "fuel_fire",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You reduce a firewood bundle into usable charcoal.",
    costs: [{ itemId: "firewood_bundle", name: "firewood bundle", required: 1 }],
    output: { itemId: "charcoal", qty: 3 },
    process: "burn",
    durationSec: 75,
  },
  {
    id: "bundle_tinder",
    name: "Bundle Tinder",
    description: "You pack dry leaves and shredded bark into tinder that wants to catch sparks.",
    category: "fuel_fire",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You pack dry leaves and shredded bark into tinder that wants to catch sparks.",
    costs: [
      { itemId: "dry_leaves", name: "dry leaves", required: 4 },
      { itemId: "bark", name: "bark", required: 1 },
      { itemId: "twig_bundle", name: "twig bundle", required: 1 },
    ],
    output: { itemId: "tinder_bundle", qty: 1 },
    process: "assemble",
    durationSec: 5,
  },
  {
    id: "tinder_bundle",
    name: "Tinder Bundle (Quick)",
    description: "dry leaves and bark bundled into a starter nest.",
    category: "fuel_fire",
    requiredContext: "hand",
    process: "assemble",
    feedbackTags: ["dry", "fire"],
    costs: [
      { itemId: "leaves", name: "dry leaves", required: 2 },
      { itemId: "bark", name: "bark", required: 1 },
    ],
  },
{
    id: "firewood_bundle",
    name: "Firewood Bundle",
    description: "branches tied into a longer-burning fuel bundle.",
    category: "fuel_fire",
    requiredContext: "hand",
    process: "assemble",
    feedbackTags: ["binding", "fuel"],
    costs: [
      { itemId: "branch", name: "branch", required: 2 },
      { itemId: "grass_fiber", name: "grass fiber", required: 1 },
    ],
  },
];
