import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const medicineRecipes: readonly RecipeInput[] = [
  {
    id: "weak_medicine",
    name: "Weak Medicine",
    description: "a bitter moss tea that steadies sickness and thirst.",
    requiresCampfire: true,
    category: "medicine",
    requiredContext: "campfire",
    process: "boil",
    feedbackTags: ["herbal", "steam"],
    costs: [
      { itemId: "clean_water", name: "clean water", required: 1 },
      { itemId: "moss", name: "moss", required: 1 },
    ],
  },
  {
    id: "bitter_tonic",
    name: "Bitter Tonic",
    description: "You boil bitter roots and herbs into a medicine that tastes like punishment.",
    category: "medicine",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You boil bitter roots and herbs into a medicine that tastes like punishment.",
    costs: [
      { itemId: "wild_root", name: "wild root", required: 1 },
      { itemId: "wild_herb", name: "wild herb", required: 1 },
      { itemId: "clean_water", name: "clean water", required: 1 },
    ],
    output: { itemId: "bitter_tonic", qty: 1 },
    process: "boil",
    durationSec: 30,
  },
  {
    id: "dried_herb",
    name: "Dried Herb",
    description: "wild herb dried until potent and storable.",
    category: "medicine",
    requiredContext: "drying_rack",
    process: "dry",
    durationSec: 15,
    discoverable: true,
    discoveryText: "The herb crumbles between your fingers but still smells sharp.",
    feedbackTags: ["herbal", "dry"],
    costs: [{ itemId: "wild_herb", name: "wild herb", required: 2 }],
    output: { itemId: "dried_herb", qty: 1 },
  },
  {
    id: "dry_herbs",
    name: "Dry Herbs (Seed)",
    description: "You dry herbs so they keep longer and brew stronger.",
    category: "medicine",
    requiredContext: "drying_rack",
    discoverable: true,
    discoveryText: "You dry herbs so they keep longer and brew stronger.",
    costs: [{ itemId: "wild_herb", name: "wild herb", required: 3 }],
    output: { itemId: "dried_herb", qty: 1 },
    process: "dry",
    durationSec: 90,
  },
  {
    id: "moss_dressing",
    name: "Moss Dressing",
    description: "damp moss pressed against fiber. absorbs and slows a minor wound.",
    category: "medicine",
    requiredContext: "hand",
    process: "assemble",
    discoverable: true,
    discoveryText: "The moss holds the fiber in place against a wound.",
    feedbackTags: ["herbal"],
    costs: [
      { itemId: "green_leaves", name: "green leaves", required: 2, substitutes: [{ itemId: "plantain_leaf", name: "plantain leaf", required: 2 }] },
      { itemId: "moss", name: "moss", required: 1 },
      { itemId: "grass_fiber", name: "grass fiber", required: 2 },
    ],
    output: { itemId: "crude_dressing", qty: 1 },
  },
  {
    id: "clean_bandage",
    name: "Clean Bandage",
    description: "You clean and fold plant material into something safe enough for a wound.",
    category: "medicine",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You clean and fold plant material into something safe enough for a wound.",
    costs: [
      { itemId: "green_leaves", name: "green leaves", required: 3 },
      { itemId: "clean_water", name: "clean water", required: 1 },
      { itemId: "binding_cord", name: "binding cord", required: 2 },
    ],
    output: { itemId: "clean_bandage", qty: 1 },
    process: "assemble",
    durationSec: 15,
  },
  {
    id: "crude_splint",
    name: "Crude Splint",
    description: "You bind sticks into a rigid support for a bad limb.",
    category: "medicine",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You bind sticks into a rigid support for a bad limb.",
    costs: [
      { itemId: "stick", name: "stick", required: 2 },
      { itemId: "binding_cord", name: "binding cord", required: 2 },
      { itemId: "bark", name: "bark", required: 1 },
    ],
    output: { itemId: "crude_splint", qty: 1 },
    process: "assemble",
    durationSec: 12,
  },
  {
    id: "ash_poultice",
    name: "Ash Poultice",
    description: "ash and herb worked into a dark paste with water. effective but uncertain.",
    category: "medicine",
    requiredContext: "primitive_work_surface",
    process: "assemble",
    durationSec: 6,
    discoverable: true,
    discoveryText: "The ash draws the herb's bitterness into the paste.",
    feedbackTags: ["herbal", "ash"],
    costs: [
      { itemId: "ash", name: "ash", required: 1 },
      { itemId: "wild_herb", name: "wild herb", required: 1 },
      { itemId: "dirty_water", name: "dirty water", required: 1 },
    ],
    output: { itemId: "crude_poultice", qty: 1 },
  },
  {
    id: "ash_paste",
    name: "Ash Paste (Seed)",
    description: "You mix ash with boiled water into a harsh cleaning paste.",
    category: "medicine",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You mix ash with boiled water into a harsh cleaning paste.",
    costs: [
      { itemId: "ash", name: "ash", required: 2 },
      { itemId: "clean_water", name: "clean water", required: 1 },
    ],
    output: { itemId: "ash_paste", qty: 1 },
    process: "assemble",
    durationSec: 8,
  },
  {
    id: "herb_poultice",
    name: "Herb Poultice (Seed)",
    description: "You crush herbs and leaves into a wet dressing for cuts.",
    category: "medicine",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You crush herbs and leaves into a wet dressing for cuts.",
    costs: [
      { itemId: "wild_herb", name: "wild herb", required: 2 },
      { itemId: "moss", name: "moss", required: 1 },
      { itemId: "clean_water", name: "clean water", required: 1 },
    ],
    output: { itemId: "herb_poultice", qty: 1 },
    process: "assemble",
    durationSec: 12,
  },
  {
    id: "yarrow_poultice",
    name: "Yarrow Poultice (Seed)",
    description: "You pack yarrow into a stronger dressing for bleeding.",
    category: "medicine",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You pack yarrow into a stronger dressing for bleeding.",
    costs: [
      { itemId: "wild_herb", name: "wild herb", required: 2 },
      { itemId: "clean_bandage", name: "clean bandage", required: 1 },
    ],
    output: { itemId: "yarrow_poultice", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
  {
    id: "essence_poultice",
    name: "Essence Poultice",
    description: "You blend vital red herbs and sticky resin into clean bandages to seal severe wounds.",
    category: "medicine",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "The paste warms against the skin and stops the bleeding.",
    costs: [
      { itemId: "red_herb", name: "red herb", required: 1 },
      { itemId: "resin", name: "resin", required: 1 },
      { itemId: "clean_bandage", name: "clean bandage", required: 1 },
    ],
    output: { itemId: "essence_poultice", qty: 1 },
    process: "assemble",
    durationSec: 15,
  },
];
