import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const processingRecipes: readonly RecipeInput[] = [
  {
    id: "stone_block",
    name: "Stone Block",
    description: "Refined block of cut stone. Used in outpost construction.",
    category: "material_processing",
    process: "assemble",
    costs: [{ itemId: "stone", name: "Raw Stone", required: 3 }],
  },
  {
    id: "plank",
    name: "Plank",
    description: "Smooth plank of sawed timber. Used in construction.",
    category: "material_processing",
    process: "assemble",
    costs: [{ itemId: "wood", name: "Wood", required: 3 }],
  },
  {
    id: "twist_grass_cord",
    name: "Twist Grass Cord",
    description: "You twist loose grass fibers into a cord that can actually hold something.",
    category: "material_processing",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You twist loose grass fibers into a cord that can actually hold something.",
    costs: [{ itemId: "grass_fiber", name: "grass fiber", required: 3 }],
    output: { itemId: "grass_cord", qty: 1 },
    process: "assemble",
    durationSec: 4,
  },
  {
    id: "twist_bark_rope",
    name: "Twist Bark Rope",
    description: "You work bark strips into a rough rope.",
    category: "material_processing",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You work bark strips into a rough rope.",
    costs: [
      { itemId: "bark", name: "bark", required: 3 },
      { itemId: "grass_cord", name: "grass cord", required: 1 },
    ],
    output: { itemId: "bark_rope", qty: 1 },
    process: "assemble",
    durationSec: 8,
  },
{
    id: "binding_cord",
    name: "Binding Cord",
    description: "fiber and bark twisted into usable cord.",
    category: "material_processing",
    requiredContext: "hand",
    process: "assemble",
    feedbackTags: ["binding"],
    costs: [
      { itemId: "grass_fiber", name: "grass fiber", required: 2 },
      { itemId: "bark", name: "bark", required: 1 },
    ],
  },
  {
    id: "copper_ingot",
    name: "Copper Ingot",
    description: "Pure smelted copper bar. Requires standing near the Campfire's heat.",
    requiresCampfire: true,
    category: "material_processing",
    requiredContext: "campfire",
    process: "heat",
    costs: [
      { itemId: "copper_ore", name: "Copper Ore", required: 3 },
      { itemId: "charcoal", name: "Charcoal", required: 1 },
    ],
  },
  {
    id: "iron_ingot",
    name: "Iron Ingot",
    description: "Refined ingot of strong iron metal. Requires standing near the Campfire's heat.",
    requiresCampfire: true,
    category: "material_processing",
    requiredContext: "campfire",
    process: "heat",
    costs: [
      { itemId: "iron_ore", name: "Iron Ore", required: 3 },
      { itemId: "charcoal", name: "Charcoal", required: 2 },
    ],
  },
  {
    id: "silver_ingot",
    name: "Silver Ingot",
    description: "Glistening sterling silver bar. Requires standing near the Campfire's heat.",
    requiresCampfire: true,
    category: "material_processing",
    requiredContext: "campfire",
    process: "heat",
    costs: [
      { itemId: "silver_ore", name: "Silver Ore", required: 3 },
      { itemId: "charcoal", name: "Charcoal", required: 3 },
    ],
  },
  {
    id: "harden_clay",
    name: "Harden Clay",
    description: "Loose clay bakes into a harder, less forgiving material.",
    category: "material_processing",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "Loose clay bakes into a harder, less forgiving material.",
    costs: [{ itemId: "clay", name: "clay", required: 1 }],
    output: { itemId: "hardened_clay", qty: 1 },
    process: "heat",
    durationSec: 40,
  },
  {
    id: "make_ash_from_leaves",
    name: "Burn Leaves To Ash",
    description: "Dry leaves flare quickly and collapse into ash.",
    category: "material_processing",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "Dry leaves flare quickly and collapse into ash.",
    costs: [{ itemId: "dry_leaves", name: "dry leaves", required: 5 }],
    output: { itemId: "ash", qty: 2 },
    process: "burn",
    durationSec: 8,
  },
  {
    id: "render_animal_fat",
    name: "Render Animal Fat",
    description: "You heat fat until it becomes a usable base for salves and fire.",
    category: "material_processing",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You heat fat until it becomes a usable base for salves and fire.",
    costs: [{ itemId: "fatty_meat", name: "fatty meat", required: 1 }],
    output: { itemId: "animal_fat", qty: 1 },
    process: "heat",
    durationSec: 25,
  },
  {
    id: "tannin_brew",
    name: "Tannin Brew",
    description: "You boil oak bark into a bitter liquid for treating hides and washing wounds.",
    category: "material_processing",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You boil oak bark into a bitter liquid for treating hides and washing wounds.",
    costs: [
      { itemId: "bark", name: "bark", required: 2 },
      { itemId: "clean_water", name: "clean water", required: 1 },
    ],
    output: { itemId: "tannin_brew", qty: 1 },
    process: "boil",
    durationSec: 35,
  },
  {
    id: "sealing_paste",
    name: "Sealing Paste",
    description: "You work mud, ash, and fiber into something that can seal gaps.",
    category: "material_processing",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You work mud, ash, and fiber into something that can seal gaps.",
    costs: [
      { itemId: "clay", name: "clay", required: 1 },
      { itemId: "ash", name: "ash", required: 1 },
      { itemId: "grass_fiber", name: "grass fiber", required: 2 },
    ],
    output: { itemId: "sealing_paste", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
  {
    id: "dry_tendon",
    name: "Dry Tendon",
    description: "The tendon tightens into stronger binding material as it dries.",
    category: "material_processing",
    requiredContext: "drying_rack",
    discoverable: true,
    discoveryText: "The tendon tightens into stronger binding material as it dries.",
    costs: [{ itemId: "tendon", name: "tendon", required: 1 }],
    output: { itemId: "dried_tendon", qty: 1 },
    process: "dry",
    durationSec: 120,
  },
  {
    id: "dry_raw_hide",
    name: "Dry Raw Hide",
    description: "You stretch and dry hide before rot claims it.",
    category: "material_processing",
    requiredContext: "drying_rack",
    discoverable: true,
    discoveryText: "You stretch and dry hide before rot claims it.",
    costs: [{ itemId: "raw_hide", name: "raw hide", required: 1 }],
    output: { itemId: "dried_hide", qty: 1 },
    process: "dry",
    durationSec: 180,
  },
  {
    id: "cure_hide",
    name: "Cure Hide",
    description: "You treat dried hide with tannins and smoke until it becomes more useful.",
    category: "material_processing",
    requiredContext: "drying_rack",
    discoverable: true,
    discoveryText: "You treat dried hide with tannins and smoke until it becomes more useful.",
    costs: [
      { itemId: "dried_hide", name: "dried hide", required: 1 },
      { itemId: "tannin_brew", name: "tannin brew", required: 1 },
    ],
    output: { itemId: "cured_hide", qty: 1 },
    process: "dry",
    durationSec: 220,
  },
];
