import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const structureRecipes: readonly RecipeInput[] = [
  {
    id: "campfire_kit",
    name: "Campfire Kit",
    description: "You arrange stones, tinder, and fuel into a place where fire can be controlled.",
    category: "structures",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You arrange stones, tinder, and fuel into a place where fire can be controlled.",
    costs: [
      { itemId: "stone", name: "stone", required: 6 },
      { itemId: "tinder_bundle", name: "tinder bundle", required: 1 },
      { itemId: "twig_bundle", name: "twig bundle", required: 1 },
    ],
    output: { itemId: "campfire_kit", qty: 1 },
    process: "assemble",
    durationSec: 12,
  },
  {
    id: "primitive_work_surface_kit",
    name: "Primitive Work Surface Kit",
    description: "You prepare a stable surface for cutting, binding, and shaping.",
    category: "structures",
    requiredContext: "hand",
    discoverable: true,
    discoveryText: "You prepare a stable surface for cutting, binding, and shaping.",
    costs: [
      { itemId: "stone", name: "stone", required: 2 },
      { itemId: "branch", name: "branch", required: 2 },
      { itemId: "bark_rope", name: "bark rope", required: 1 },
    ],
    output: { itemId: "primitive_work_surface_kit", qty: 1 },
    process: "assemble",
    durationSec: 18,
  },
  {
    id: "drying_rack_kit",
    name: "Drying Rack Kit",
    description: "You lash branches into a frame for air and time to work.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You lash branches into a frame for air and time to work.",
    costs: [
      { itemId: "branch", name: "branch", required: 4 },
      { itemId: "grass_cord", name: "grass cord", required: 3 },
      { itemId: "stick", name: "stick", required: 4 },
    ],
    output: { itemId: "drying_rack_kit", qty: 1 },
    process: "assemble",
    durationSec: 25,
  },
  {
    id: "marker_sign_kit",
    name: "Marker Sign Kit",
    description: "You make a sign that can hold a short player-written message.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You make a sign that can hold a short player-written message.",
    costs: [
      { itemId: "stick", name: "stick", required: 1 },
      { itemId: "bark", name: "bark", required: 2 },
      { itemId: "charcoal", name: "charcoal", required: 1 },
    ],
    output: { itemId: "marker_sign_kit", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
  {
    id: "crude_shelter_kit",
    name: "Crude Shelter Kit",
    description: "You bundle the frame and covering needed for a crude lean-to.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You bundle the frame and covering needed for a crude lean-to.",
    costs: [
      { itemId: "branch", name: "branch", required: 5 },
      { itemId: "green_leaves", name: "green leaves", required: 8 },
      { itemId: "bark_rope", name: "bark rope", required: 2 },
      { itemId: "vine", name: "vine", required: 2 },
    ],
    output: { itemId: "crude_shelter_kit", qty: 1 },
    process: "assemble",
    durationSec: 45,
  },
  {
    id: "storage_pile_kit",
    name: "Storage Pile Kit",
    description: "You mark and reinforce a place for camp storage.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You mark and reinforce a place for camp storage.",
    costs: [
      { itemId: "branch", name: "branch", required: 3 },
      { itemId: "bark", name: "bark", required: 4 },
      { itemId: "vine", name: "vine", required: 2 },
    ],
    output: { itemId: "storage_pile_kit", qty: 1 },
    process: "assemble",
    durationSec: 25,
  },
  {
    id: "spike_barrier_kit",
    name: "Spike Barrier Kit",
    description: "You sharpen stakes and lash them into an ugly argument against teeth.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You sharpen stakes and lash them into an ugly argument against teeth.",
    costs: [
      { itemId: "stick", name: "stick", required: 8 },
      { itemId: "branch", name: "branch", required: 3 },
      { itemId: "bark_rope", name: "bark rope", required: 2 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
    ],
    output: { itemId: "spike_barrier_kit", qty: 1 },
    process: "assemble",
    durationSec: 40,
  },
  {
    id: "rain_catcher_kit",
    name: "Rain Catcher Kit",
    description: "You stretch hide over a frame to catch what the sky gives.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You stretch hide over a frame to catch what the sky gives.",
    costs: [
      { itemId: "branch", name: "branch", required: 4 },
      { itemId: "cured_hide", name: "cured hide", required: 1 },
      { itemId: "bark_rope", name: "bark rope", required: 2 },
      { itemId: "clay", name: "clay", required: 2 },
    ],
    output: { itemId: "rain_catcher_kit", qty: 1 },
    process: "assemble",
    durationSec: 40,
  },
  {
    id: "meat_smoking_rack_kit",
    name: "Meat Smoking Rack Kit",
    description: "You prepare a rack that feeds smoke around meat instead of burning it.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You prepare a rack that feeds smoke around meat instead of burning it.",
    costs: [
      { itemId: "branch", name: "branch", required: 5 },
      { itemId: "grass_cord", name: "grass cord", required: 4 },
      { itemId: "clay", name: "clay", required: 2 },
      { itemId: "stone", name: "stone", required: 4 },
    ],
    output: { itemId: "meat_smoking_rack_kit", qty: 1 },
    process: "assemble",
    durationSec: 45,
  },
  {
    id: "simple_bedroll",
    name: "Simple Bedroll",
    description: "You layer leaves and hide into something better than cold dirt.",
    category: "structures",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You layer leaves and hide into something better than cold dirt.",
    costs: [
      { itemId: "dried_hide", name: "dried hide", required: 1 },
      { itemId: "green_leaves", name: "green leaves", required: 8 },
      { itemId: "grass_cord", name: "grass cord", required: 6 },
      { itemId: "moss", name: "moss", required: 4 },
    ],
    output: { itemId: "simple_bedroll", qty: 1 },
    process: "assemble",
    durationSec: 30,
  },
];
