import type { RecipeInput } from "$lib/domain/crafting/recipe-types";

export const toolRecipes: readonly RecipeInput[] = [
  {
    id: "flint_axe",
    name: "Flint Axe",
    description: "a crude cutting tool for taking down small trees.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    process: "assemble",
    feedbackTags: ["binding", "tool"],
    tiered: true,
    costs: [
      { itemId: "stick", name: "stick", required: 1 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
      { itemId: "grass_fiber", name: "grass fiber", required: 1 },
    ],
    output: { itemId: "flint_axe", qty: 1 },
    durationSec: 15,
  },
  {
    id: "shape_stone_blade",
    name: "Shape Stone Blade",
    description: "You strike and scrape stone until one edge becomes useful.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You strike and scrape stone until one edge becomes useful.",
    costs: [
      { itemId: "flint_shard", name: "flint shard", required: 1 },
      { itemId: "stone", name: "stone", required: 1 },
    ],
    output: { itemId: "stone_blade", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
  {
    id: "crude_knife",
    name: "Crude Knife",
    description: "You bind a flint edge to a stick with rough cord.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "The flint bites cleanly once it is bound tight.",
    feedbackTags: ["binding", "tool", "sharp"],
    tiered: true,
    costs: [
      { itemId: "stick", name: "stick", required: 1 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
      { itemId: "grass_fiber", name: "grass fiber", required: 1 },
    ],
    output: { itemId: "crude_knife", qty: 1 },
    process: "assemble",
    durationSec: 15,
  },
  {
    id: "stone_axe",
    name: "Stone Axe",
    description: "You wedge a stone blade into a branch and lash it tight.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You wedge a stone blade into a branch and lash it tight.",
    feedbackTags: ["binding", "tool"],
    tiered: true,
    costs: [
      { itemId: "branch", name: "branch", required: 1 },
      { itemId: "stone_blade", name: "stone blade", required: 1 },
      { itemId: "bark_rope", name: "bark rope", required: 1 },
      { itemId: "resin", name: "resin", required: 1 },
    ],
    output: { itemId: "stone_axe", qty: 1 },
    process: "assemble",
    durationSec: 25,
  },
  {
    id: "wooden_spear",
    name: "Wooden Spear",
    description: "You sharpen a long branch into a weapon meant for distance.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You sharpen a long branch into a weapon meant for distance.",
    tiered: true,
    costs: [
      { itemId: "branch", name: "branch", required: 2 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
      { itemId: "grass_cord", name: "grass cord", required: 1 },
    ],
    output: { itemId: "wooden_spear", qty: 1 },
    process: "assemble",
    durationSec: 18,
  },
  {
    id: "hardened_spear",
    name: "Hardened Spear",
    description: "You finish a spear point with heat and scraping until it holds better.",
    category: "tools",
    requiredContext: "campfire",
    discoverable: true,
    discoveryText: "You finish a spear point with heat and scraping until it holds better.",
    tiered: true,
    costs: [
      { itemId: "wooden_spear", name: "wooden spear", required: 1 },
      { itemId: "charcoal", name: "charcoal", required: 1 },
    ],
    output: { itemId: "hardened_spear", qty: 1 },
    process: "heat",
    durationSec: 30,
  },
  {
    id: "bone_needle",
    name: "Bone Needle",
    description: "You scrape a bone shard into a needle for hidework.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You scrape a bone shard into a needle for hidework.",
    // Crafting-ingredient tool, not gear the player wears/wields — excluded from auto-tiering.
    tiered: false,
    costs: [
      { itemId: "small_bone", name: "small bone", required: 1 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
    ],
    output: { itemId: "bone_needle", qty: 1 },
    process: "assemble",
    durationSec: 12,
  },
  {
    id: "bone_hook",
    name: "Bone Hook",
    description: "You carve a bone shard into a small hook.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You carve a bone shard into a small hook.",
    // Crafting-ingredient tool, not gear the player wears/wields — excluded from auto-tiering.
    tiered: false,
    costs: [
      { itemId: "small_bone", name: "small bone", required: 1 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
    ],
    output: { itemId: "bone_hook", qty: 1 },
    process: "assemble",
    durationSec: 10,
  },
  {
    id: "flint_pickaxe",
    name: "Flint Pickaxe",
    description: "a crude mining tool for later stone work.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    process: "assemble",
    feedbackTags: ["binding", "tool"],
    tiered: true,
    costs: [
      { itemId: "stick", name: "stick", required: 1 },
      { itemId: "flint_shard", name: "flint shard", required: 1 },
      { itemId: "grass_fiber", name: "grass fiber", required: 1 },
    ],
    output: { itemId: "flint_pickaxe", qty: 1 },
    durationSec: 15,
  },
  {
    id: "crude_torch",
    name: "Crude Torch",
    description: "You wrap resin and bark around a stick to carry fire with you.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "You wrap resin and bark around a stick to carry fire with you.",
    costs: [
      { itemId: "stick", name: "stick", required: 1 },
      { itemId: "resin", name: "resin", required: 2 },
      { itemId: "bark", name: "bark", required: 1 },
      { itemId: "grass_cord", name: "grass cord", required: 1 },
    ],
    output: { itemId: "crude_torch", qty: 1 },
    process: "assemble",
    durationSec: 12,
  },
  {
    id: "copper_lantern",
    name: "Copper Lantern",
    description: "You forge a copper plate housing and add rendered fat as a fuel source.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "The lantern glows steadily, shielded from drafts.",
    costs: [
      { itemId: "copper_ingot", name: "copper ingot", required: 1 },
      { itemId: "rendered_fat", name: "rendered fat", required: 1 },
      { itemId: "grass_cord", name: "grass cord", required: 1 },
    ],
    output: { itemId: "copper_lantern", qty: 1 },
    process: "assemble",
    durationSec: 30,
  },
  {
    id: "copper_spear",
    name: "Copper Spear",
    description: "You forge a heavy copper tip and lash it securely to an ash branch.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "The copper tip is heavy but pierces deep.",
    tiered: true,
    costs: [
      { itemId: "copper_ingot", name: "copper ingot", required: 2 },
      { itemId: "branch", name: "branch", required: 2 },
      { itemId: "bark_rope", name: "bark rope", required: 1 },
    ],
    output: { itemId: "copper_spear", qty: 1 },
    process: "assemble",
    durationSec: 25,
  },
  {
    id: "bone_dagger",
    name: "Bone Dagger",
    description: "You grind down a predator fang and mount it in a sturdy antler handle.",
    category: "tools",
    requiredContext: "primitive_work_surface",
    discoverable: true,
    discoveryText: "The curved fang makes a vicious and quick dagger.",
    tiered: true,
    costs: [
      { itemId: "fang", name: "fang", required: 1 },
      { itemId: "antler", name: "antler", required: 1 },
      { itemId: "dried_tendon", name: "dried tendon", required: 1 },
    ],
    output: { itemId: "bone_dagger", qty: 1 },
    process: "assemble",
    durationSec: 15,
  },
];
