import { Category, Rarity, itemId, type ItemDefinition } from "./item-types";
import { Item } from "./item-builder";
import { buildItemTraitIndex, defineItems } from "./item-registry";
import {
  AddStatus,
  ChanceOfVitals,
  ClearAllStatuses,
  RestoreHp,
  RestoreThirst,
  TransformInto,
} from "./item-effects";
import { Boilable, Consumable, Decayable, Flammable, TemperatureSensitive } from "./item-traits";
import { StatusId } from "$lib/domain/systems/status-types";

export const ITEM_DEFINITIONS: Record<string, ItemDefinition> = defineItems({
  stone: Item({
    id: itemId("stone"),
    name: "Stone",
    description: "A raw chunk of stone. Rough and heavy.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 30 },
    iconUrl: "/assets/icons/rock.png",
  }),
  stick: Item({
    id: itemId("stick"),
    name: "Stick",
    description: "A dry fallen stick. Light enough to carry by the handful.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pocket", weight: 0.2, stackLimit: 20 },
    iconUrl: "/assets/icons/twigs.png",
  }).with(
    Flammable({
      ignitionTemp: 95,
      burnDurationSec: 6,
      effect: TransformInto(itemId("ash")),
    }),
  ),
  branch: Item({
    id: itemId("branch"),
    name: "Branch",
    description: "A thicker branch, useful as crude structure or tool stock.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 0.8, stackLimit: 12 },
  }).with(
    Flammable({
      ignitionTemp: 105,
      burnDurationSec: 10,
      effect: TransformInto(itemId("charcoal")),
    }),
  ),
  flint_shard: Item({
    id: itemId("flint_shard"),
    name: "Flint Shard",
    description: "A jagged stone shard with a pale edge.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pocket", weight: 0.15, stackLimit: 20 },
    iconUrl: "/assets/icons/flint_shard.png",
  }),
  grass_fiber: Item({
    id: itemId("grass_fiber"),
    name: "Grass Fiber",
    description: "Pulled strands of tough grass that can bind small tools.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 40 },
    iconUrl: "/assets/icons/fiber.png",
  }),
  wet_fiber: Item({
    id: itemId("wet_fiber"),
    name: "Wet Fiber",
    description: "Soaked grass fiber that needs drying before it binds well.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.07, stackLimit: 40 },
    iconUrl: "/assets/icons/fiber.png",
  }),
  leaves: Item({
    id: itemId("leaves"),
    name: "Leaves",
    description: "Dry leaf litter. Useful as tinder, terrible near flame.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.03, stackLimit: 50 },
    iconUrl: "/assets/icons/leaves.png",
  }).with(
    Flammable({
      ignitionTemp: 70,
      burnDurationSec: 3,
      effect: TransformInto(itemId("ash")),
    }),
  ),
  wet_leaves: Item({
    id: itemId("wet_leaves"),
    name: "Wet Leaves",
    description: "Sodden leaves. Useless as tinder until dried.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 50 },
    iconUrl: "/assets/icons/leaves.png",
  }),
  bark: Item({
    id: itemId("bark"),
    name: "Bark",
    description: "Rough bark stripped from fallen wood.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.1, stackLimit: 30 },
    iconUrl: "/assets/icons/tree_bark.png",
  }).with(
    Flammable({
      ignitionTemp: 90,
      burnDurationSec: 5,
      effect: TransformInto(itemId("charcoal")),
    }),
  ),
  berries: Item({
    id: itemId("berries"),
    name: "Berries",
    description: "Small dark berries with a tart smell.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 30 },
    iconUrl: "/assets/icons/berries.png",
  }).with(
    Consumable({
      verb: "eat",
      onConsume: [RestoreHp(2)],
    }),
    Decayable({
      lifespanSec: 240,
      effect: TransformInto(itemId("volatile_ash")),
    }),
  ),
  mushroom: Item({
    id: itemId("mushroom"),
    name: "Mushroom",
    description: "A pale forest mushroom with damp gills.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.08, stackLimit: 20 },
    iconUrl: "/assets/icons/mushroom.png",
  }).with(
    Consumable({
      verb: "eat",
      onConsume: [RestoreHp(1), ChanceOfVitals(0.35, AddStatus(StatusId.Poison, 45))],
    }),
    Decayable({
      lifespanSec: 180,
      effect: TransformInto(itemId("volatile_ash")),
    }),
  ),
  clay: Item({
    id: itemId("clay"),
    name: "Clay",
    description: "Wet clay that holds shape when pressed.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.8, stackLimit: 20 },
    iconUrl: "/assets/icons/mud.png",
  }).with(
    TemperatureSensitive({
      minSafeTemp: -100,
      maxSafeTemp: 90,
      effect: TransformInto(itemId("hardened_clay")),
    }),
  ),
  hardened_clay: Item({
    id: itemId("hardened_clay"),
    name: "Hardened Clay",
    description: "Clay baked firm enough for crude containers and structure.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 20 },
  }),
  moss: Item({
    id: itemId("moss"),
    name: "Moss",
    description: "Soft damp moss with a clean, green scent.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.04, stackLimit: 30 },
    iconUrl: "/assets/icons/wild_herb.png",
  }),
  wild_herb: Item({
    id: itemId("wild_herb"),
    name: "Wild Herb",
    description: "A sharp-smelling forest herb that may help when steeped or dried.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.04, stackLimit: 30 },
    iconUrl: "/assets/icons/wild_herb.png",
  }),
  dried_herb: Item({
    id: itemId("dried_herb"),
    name: "Dried Herb",
    description: "Preserved herb with a stronger bitter scent.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.02, stackLimit: 40 },
    iconUrl: "/assets/icons/wild_herb.png",
  }),
  ash: Item({
    id: itemId("ash"),
    name: "Ash",
    description: "Fine grey ash left by burned tinder.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    physical: { carryClass: "pocket", weight: 0.02, stackLimit: 50 },
  }),
  weak_medicine: Item({
    id: itemId("weak_medicine"),
    name: "Weak Medicine",
    description: "A bitter moss tea that steadies the body a little.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    physical: { carryClass: "pocket", weight: 0.25, stackLimit: 10 },
  }).with(
    Consumable({
      verb: "drink",
      onConsume: [RestoreHp(10), RestoreThirst(10)],
    }),
  ),
  copper_ore: Item({
    id: itemId("copper_ore"),
    name: "Copper Ore",
    description: "Veins of copper running through rock.",
    rarity: Rarity.Common,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.4, stackLimit: 20 },
  }),
  raw_meat: Item({
    id: itemId("raw_meat"),
    name: "Raw Meat",
    description: "Fresh meat. Edible if you are desperate, smarter if cooked or dried.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pack", weight: 0.4, stackLimit: 12 },
  }).with(
    Consumable({
      verb: "eat",
      onConsume: [RestoreHp(4), ChanceOfVitals(0.3, AddStatus(StatusId.Sickness, 45))],
    }),
    Decayable({
      lifespanSec: 180,
      effect: TransformInto(itemId("volatile_ash")),
    }),
  ),
  cooked_meat: Item({
    id: itemId("cooked_meat"),
    name: "Cooked Meat",
    description: "Meat cooked over flame. Rough, hot, and much safer.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pack", weight: 0.35, stackLimit: 12 },
  }).with(
    Consumable({
      verb: "eat",
      onConsume: [RestoreHp(12)],
    }),
  ),
  dried_meat: Item({
    id: itemId("dried_meat"),
    name: "Dried Meat",
    description: "Tough preserved meat for longer survival runs.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pack", weight: 0.25, stackLimit: 20 },
  }).with(
    Consumable({
      verb: "eat",
      onConsume: [RestoreHp(8)],
    }),
  ),
  tinder_bundle: Item({
    id: itemId("tinder_bundle"),
    name: "Tinder Bundle",
    description: "A little nest of dry leaf and bark for coaxing flame.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.05, stackLimit: 20 },
    iconUrl: "/assets/icons/leaves.png",
  }).with(
    Flammable({
      ignitionTemp: 55,
      burnDurationSec: 4,
      effect: TransformInto(itemId("ash")),
    }),
  ),
  firewood_bundle: Item({
    id: itemId("firewood_bundle"),
    name: "Firewood Bundle",
    description: "Tied branches that feed a campfire longer than loose sticks.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.8, stackLimit: 8 },
  }).with(
    Flammable({
      ignitionTemp: 105,
      burnDurationSec: 24,
      effect: TransformInto(itemId("charcoal")),
    }),
  ),
  binding_cord: Item({
    id: itemId("binding_cord"),
    name: "Binding Cord",
    description: "Twisted fiber and bark, good enough for crude tools.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.06, stackLimit: 30 },
    iconUrl: "/assets/icons/fiber.png",
  }),
  crude_knife: Item({
    id: itemId("crude_knife"),
    name: "Crude Knife",
    description: "A flint edge bound into a small cutting tool.",
    icon: "knife",
    rarity: Rarity.Common,
    category: Category.Tool,
    physical: { carryClass: "pocket", weight: 0.5, stackLimit: 1 },
  }),
  mud: Item({
    id: itemId("mud"),
    name: "Mud",
    description: "Wet earth from a water edge. Messy, but it seals gaps.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 20 },
    iconUrl: "/assets/icons/mud.png",
  }),
  sealing_paste: Item({
    id: itemId("sealing_paste"),
    name: "Sealing Paste",
    description: "Mud and ash worked into a dark paste.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.45, stackLimit: 20 },
  }),
  iron_ore: Item({
    id: itemId("iron_ore"),
    name: "Iron Ore",
    description: "Deep-vein iron with crystalline structure.",
    rarity: Rarity.Uncommon,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.6, stackLimit: 20 },
  }),
  silver_ore: Item({
    id: itemId("silver_ore"),
    name: "Silver Ore",
    description: "Shining silver ore, cool to the touch.",
    rarity: Rarity.Rare,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1.3, stackLimit: 20 },
  }),
  oak_wood: Item({
    id: itemId("oak_wood"),
    name: "Oak Wood",
    description: "A sturdy log of raw oak timber.",
    rarity: Rarity.Common,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.5, stackLimit: 20 },
  }).with(
    Flammable({
      ignitionTemp: 120,
      burnDurationSec: 15,
      effect: TransformInto(itemId("charcoal")),
    }),
  ),
  spruce_wood: Item({
    id: itemId("spruce_wood"),
    name: "Spruce Wood",
    description: "Softwood log, smells of mountain pine.",
    rarity: Rarity.Uncommon,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 20 },
  }),
  palm_wood: Item({
    id: itemId("palm_wood"),
    name: "Palm Wood",
    description: "Fibrous timber from tropical shores.",
    rarity: Rarity.Rare,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.1, stackLimit: 20 },
  }),
  pine_wood: Item({
    id: itemId("pine_wood"),
    name: "Pine Wood",
    description: "Dense hardwood from ancient pinelands.",
    rarity: Rarity.Legendary,
    category: Category.Timber,
    physical: { carryClass: "pack", weight: 1.7, stackLimit: 20 },
  }),
  stone_block: Item({
    id: itemId("stone_block"),
    name: "Stone Block",
    description: "Refined block of cut stone.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 2, stackLimit: 20 },
  }),
  copper_ingot: Item({
    id: itemId("copper_ingot"),
    name: "Copper Ingot",
    description: "A pure bar of smelted copper.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 1, stackLimit: 20 },
  }),
  iron_ingot: Item({
    id: itemId("iron_ingot"),
    name: "Iron Ingot",
    description: "A solid bar of refined iron.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 20 },
  }),
  silver_ingot: Item({
    id: itemId("silver_ingot"),
    name: "Silver Ingot",
    description: "A glistening bar of sterling silver.",
    rarity: Rarity.Rare,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 1, stackLimit: 20 },
  }),
  oak_plank: Item({
    id: itemId("oak_plank"),
    name: "Oak Plank",
    description: "Smooth plank of sawed oak wood.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.6, stackLimit: 30 },
  }),
  spruce_plank: Item({
    id: itemId("spruce_plank"),
    name: "Spruce Plank",
    description: "Clean plank of sawed spruce wood.",
    rarity: Rarity.Uncommon,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.5, stackLimit: 30 },
  }),
  palm_plank: Item({
    id: itemId("palm_plank"),
    name: "Palm Plank",
    description: "Flexible plank of sawed palm wood.",
    rarity: Rarity.Rare,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.5, stackLimit: 30 },
  }),
  pine_plank: Item({
    id: itemId("pine_plank"),
    name: "Pine Plank",
    description: "Resilient plank of sawed pine wood.",
    rarity: Rarity.Legendary,
    category: Category.Component,
    physical: { carryClass: "pack", weight: 0.7, stackLimit: 30 },
  }),
  // --- Tools -----------------------------------------------------------------
  // Two families, five tiers each. Pickaxes (⛏️) mine ore/stone; axes (🪓) chop
  // trees. The id substring ("pickaxe"/"axe") is what the gather gate keys off,
  // so every pickaxe id must contain "pickaxe" and every axe id must contain
  // "axe" without "pickaxe". Emoji icons are placeholders until sprites exist.
  starter_pickaxe: Item({
    id: itemId("starter_pickaxe"),
    name: "Starter Pickaxe",
    description: "A tired pickaxe with a worn iron head.",
    icon: "⛏️",
    rarity: Rarity.Common,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 2, stackLimit: 1 },
  }),
  starter_axe: Item({
    id: itemId("starter_axe"),
    name: "Starter Axe",
    description: "A simple hand axe with a notched blade.",
    icon: "🪓",
    rarity: Rarity.Common,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.6, stackLimit: 1 },
  }),
  stone_pickaxe: Item({
    id: itemId("stone_pickaxe"),
    name: "Stone Pickaxe",
    description: "A stone pick lashed to a wooden haft.",
    icon: "⛏️",
    rarity: Rarity.Uncommon,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.8, stackLimit: 1 },
  }),
  stone_axe: Item({
    id: itemId("stone_axe"),
    name: "Stone Axe",
    description: "A heavy axe with a polished stone head.",
    icon: "🪓",
    rarity: Rarity.Uncommon,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.8, stackLimit: 1 },
  }),
  flint_pickaxe: Item({
    id: itemId("flint_pickaxe"),
    name: "Flint Pickaxe",
    description: "A knapped flint pick bound with twine.",
    icon: "⛏️",
    rarity: Rarity.Uncommon,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.4, stackLimit: 1 },
  }),
  flint_axe: Item({
    id: itemId("flint_axe"),
    name: "Flint Axe",
    description: "A simple axe made of sharp flint stone and wood.",
    icon: "🪓",
    rarity: Rarity.Uncommon,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.2, stackLimit: 1 },
  }),
  copper_pickaxe: Item({
    id: itemId("copper_pickaxe"),
    name: "Copper Pickaxe",
    description: "Malleable copper pickaxe. Gleams brightly.",
    icon: "⛏️",
    rarity: Rarity.Rare,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.7, stackLimit: 1 },
  }),
  copper_axe: Item({
    id: itemId("copper_axe"),
    name: "Copper Axe",
    description: "A copper woodsman axe with a sharp edge.",
    icon: "🪓",
    rarity: Rarity.Rare,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.5, stackLimit: 1 },
  }),
  iron_pickaxe: Item({
    id: itemId("iron_pickaxe"),
    name: "Iron Pickaxe",
    description: "A heavy, professional iron mining tool.",
    icon: "⛏️",
    rarity: Rarity.Legendary,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 2.2, stackLimit: 1 },
  }),
  iron_axe: Item({
    id: itemId("iron_axe"),
    name: "Iron Axe",
    description: "Tempered iron head on a sturdy oak shaft.",
    icon: "🪓",
    rarity: Rarity.Legendary,
    category: Category.Tool,
    physical: { carryClass: "pack", weight: 1.9, stackLimit: 1 },
  }),
  ice_block: Item({
    id: itemId("ice_block"),
    name: "Ice Block",
    description: "A solid, freezing block of glacial ice. Melts rapidly in warm areas.",
    rarity: Rarity.Uncommon,
    category: Category.Mineral,
    physical: { carryClass: "pack", weight: 1, stackLimit: 10 },
  }).with(
    TemperatureSensitive({
      minSafeTemp: -100,
      maxSafeTemp: 0,
      effect: TransformInto(itemId("clean_water")),
    }),
  ),
  ghost_lily: Item({
    id: itemId("ghost_lily"),
    name: "Ghost Lily",
    description: "Translucent white flower found near Blight zones. Wilts within hours of picking.",
    rarity: Rarity.Rare,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.03, stackLimit: 10 },
  }).with(
    Decayable({
      lifespanSec: 60,
      effect: TransformInto(itemId("volatile_ash")),
    }),
  ),
  charcoal: Item({
    id: itemId("charcoal"),
    name: "Charcoal",
    description: "Slow-burned wood. Hotter and cleaner than coal.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.2, stackLimit: 30 },
    iconUrl: "/assets/icons/coal.png",
  }),
  volatile_ash: Item({
    id: itemId("volatile_ash"),
    name: "Volatile Ash",
    description: "Grey, inert ash residue from failed Crucible synthesis or decay.",
    rarity: Rarity.Common,
    category: Category.Reagent,
    physical: { carryClass: "pocket", weight: 0.02, stackLimit: 50 },
  }),
  dried_berries: Item({
    id: itemId("dried_berries"),
    name: "Dried Berries",
    description: "Dried, preserved berries. Chewy and lasts much longer.",
    rarity: Rarity.Common,
    category: Category.Herb,
    physical: { carryClass: "pocket", weight: 0.03, stackLimit: 40 },
    iconUrl: "/assets/icons/berries.png",
  }).with(
    Consumable({
      verb: "eat",
      onConsume: [RestoreHp(4)],
    }),
  ),
  clean_water: Item({
    id: itemId("clean_water"),
    name: "Clean Water",
    description: "Water that has been boiled and condensed to remove essence taint.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.25, stackLimit: 10 },
  }).with(
    Consumable({
      verb: "drink",
      onConsume: [RestoreThirst(60)],
    }),
  ),
  dirty_water: Item({
    id: itemId("dirty_water"),
    name: "Dirty Water",
    description: "Murky water with debris drifting in it. It smells faintly of rot.",
    rarity: Rarity.Common,
    category: Category.Component,
    physical: { carryClass: "pocket", weight: 0.25, stackLimit: 10 },
  }).with(
    Consumable({
      verb: "drink",
      onConsume: [RestoreThirst(35), ChanceOfVitals(0.45, AddStatus(StatusId.Sickness, 60))],
    }),
    Boilable({
      minTemp: 80,
      durationSec: 4,
      effect: TransformInto(itemId("clean_water")),
    }),
  ),
  debug_panacea: Item({
    id: itemId("debug_panacea"),
    name: "Debug Panacea",
    description: "A vial of impossible medicine. Cures everything. Not found in nature.",
    rarity: Rarity.Legendary,
    category: Category.Reagent,
    physical: { carryClass: "pocket", weight: 0.1, stackLimit: 5 },
  }).with(
    Consumable({
      verb: "drink",
      onConsume: [ClearAllStatuses(), RestoreThirst(100), RestoreHp(100)],
    }),
  ),
});

export const ITEM_TRAIT_INDEX = buildItemTraitIndex(ITEM_DEFINITIONS);

/** Looks up a canonical item definition by id, or `undefined` if unknown. */
export function getItemDef(id: string): ItemDefinition | undefined {
  return ITEM_DEFINITIONS[id];
}
